apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  template:
    spec:
      containers:
        - name: example-job-container
          image: busybox:latest
          args:
            - /bin/sh
            - -c
            - echo "Hello from example job"
      restartPolicy: Never
  backoffLimit: 3
