apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-resources-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-resources-app
  template:
    metadata:
      labels:
        app: example-resources-app
    spec:
      containers:
        - name: example-resources-container
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
