apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  schedule: "*/5 * * * *" # every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: example-cron-container
              image: busybox:latest
              args:
                - /bin/sh
                - -c
                - date; echo "Hello from example cronjob"
          restartPolicy: OnFailure
