apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-volume-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-volume-app
  template:
    metadata:
      labels:
        app: example-volume-app
    spec:
      containers:
        - name: example-volume-container
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: example-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: example-volume
          emptyDir: {}
